apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc-{{.Values.yourname}}
      containers:
      - name: wordpress
        image: bitnami/wordpress:latest
        imagePullPolicy: IfNotPresent

        volumeMounts:
        - name: wordpress-storage
          mountPath: /bitnami/wordpress

        env:
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-credentials
              key: username

        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-credentials
              key: password 

        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: wp_dbname

        - name: WORDPRESS_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: wp_dbhost

        - name: WORDPRESS_DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: wp_dbport
